### ISSUE TITLE
Coordinate system mismatch

### ISSUE THREAD

**Issue by Sognus** [RaidcoreGG/TyriaStreetview#1]
- When creating panorama, it depends on how panorama texture is located
- Particulary, for eye of the north calculation of arrow positions is correct but since camera location is considered Point [0, 0, 0], render of position is wrong.

Possible solution: 
- Move camera always to panorama location
- Recalculate all vector operations to vector operations relative to panorama location instead assuming camera will always be in [0, 0, 0]

**Comment by Sognus** [comment]
Possible place that needs code modifued
https://github.com/RaidcoreGG/TyriaStreetview/blob/react/src/components/Panorama/Panorama.js#L88

**Comment by Sognus** [comment]
Issue possibly fixed in [55f12c2](https://github.com/RaidcoreGG/TyriaStreetview/commit/55f12c23a7d1438da8cdcb50437d7a86a1cf150d) with some twists.

There is no way to determine what was texture offset from panorama renderer. For example offset of panorama with ID pano_queensdale_shaemoor is 29.5. 

I added support for rotation. When rotation is not specified, zero offset is assumed. To correctly display panorama arrows, all misaligned panorama textures must either provide information about correct rotation offset or new texture with no offset needs to be created. 

@DeltaxHunter

**Comment by DeltaRaidcore** [comment]
I will try to add data to each (estimates within a few degrees) or recreate them. I might still have the source files.
